language: cpp

compiler:
  - g++

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  
  - sudo apt-get update -qq

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

script: 
  - make
